language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t rtyx/docker-react-cv -f Dockerfile.dev .

script:
    - docker run -e CI=true rtyx/docker-react-cv npm run test -- --coverage
