language: generic
sudo: required
services: 
	- docker

before_install:
	- docker build -t rtyx/docker-react-cv -f Dockerfile.dev .

script:
	- docker run -it -e CI=true rtyx/docker-react-cv yarn test -coverage
