version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
#  tests:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    volumes:
#    - /app/node_modules
#    - .:/app
#    command: ["yarn", "test"]
#  cypress:
#    build:
#      context: .
#      dockerfile: Dockerfile.cypress
#    depends_on:
#      - frontend
#    environment:
#      - CYPRESS_baseUrl=http://frontend:3000
#    working_dir: /app
#    volumes:
#      - /app/node_modules
#      - .:/app
#    restart: on-failure


